### ISSUE TITLE
Key Error with Bluesky

### ISSUE THREAD

**Issue by vexillia** [woodruffw/autopost#37]
I'm using this autopost.toml 

Anything obvioussconfig:

```
[[backend]]
type = "Bluesky"
name = "@vexillia.me.uk@bluesky"
username = "vexillia.me.uk"
password = { type = "Environment", variable = "***********" }
```

With this command

`autopost --config-file "./.autopost.toml" --dry-run atom https://blog.vexillia.me.uk/feeds/posts/default`

And I get Key Error: '***********'

I have tried three app passwords.  All give the same error.

Anything obviously wrong?

**Comment by vexillia** [comment]
Forgot to mention it's installed via pipx as I'm using Xubuntu 24.04.

**Comment by woodruffw** [comment]
> Anything obviously wrong?

Is `variable` your hardcoded password, or an environment variable?

It needs to be the name of an environment variable, if you set `type = "Environment"`. If you want to hardcode a password, you should use:

```toml
password = { type = "Embedded", value = "***********" }
```

**Comment by vexillia** [comment]
Yay!  Working.  Thanks.

**Comment by vexillia** [comment]
:-)

**Comment by vexillia** [comment]
Yay!  Working.  Thanks.

**Comment by woodruffw** [comment]
No problem!
