### ISSUE TITLE
Feature request: Add tags to feed items

### ISSUE THREAD

**Issue by vexillia** [woodruffw/autopost#41]
I've been using [feediverse](https://github.com/edsu/feediverse) to autopost to the Fediverse.  It 
- uses existing tags from the items
- allows you to add tags to each item (useful for comments and untag items)

![Screenshot_2024-11-13_09-07-17](https://github.com/user-attachments/assets/775497b2-a156-4cb1-b3d6-0b6cbc980bc2)

Any chance of doing this with autopost?

**Comment by woodruffw** [comment]
Thanks for the request @vexillia. Could you say a bit more about what you're expecting here? 

Per the [examples](https://github.com/woodruffw/autopost#examples), we _do_ support `--tags` to manually specify tags to add to each post. I believe that only works with `autopost manual`, though, so if you're interested in it for `autopost atom` we could consider adding that 🙂

**Comment by vexillia** [comment]
OK.  With feediverse I can specify the template for the post to include tags from the item (if they exist) and add certain tags to every post as follows:

`template: "{title} \n{link} \n{hashtags} #viaRSS\n"`
`template: "{title} \n{link} \n{hashtags} #BlogComment #viaRSS\n"`

This produces:

![Screenshot_2024-11-13_17-02-37](https://github.com/user-attachments/assets/170ee9a7-13be-4ee9-baf5-dfafce950782)

So when autoposting (not manual), I'm interested in an  equivalent to the {hashtags} switch and an ability to add tags like #viaRSS to every post.  

I'm not bothered about other formatting options (but they would be nice). :-)

**Comment by woodruffw** [comment]
Gotcha, thanks. Yeah, I think we could enable that by adding `--tags` to `autopost atom`, which would append any explicitly specified tags to the set pulled from the feed.

**Comment by vexillia** [comment]
At the moment I'm not getting any tags if they exist within the item with just:

`autopost atom feed`

Is that right?

![Screenshot_2024-11-13_17-12-53](https://github.com/user-attachments/assets/9c9e66e9-972d-4bcc-a7a4-2dd644bf4ee9)

**Comment by woodruffw** [comment]
> Is that right?

That sounds like a bug -- `autopost atom` should always pull the feed's tags. Could you share an example entry from the feed? It's possible that the tags aren't structured correctly (there's a lot of invalid Atom RSS in the wild).

**Comment by vexillia** [comment]
Here's a snippet showing the tags:

```
<link rel='replies' type='application/atom+xml' href='https://blog.vexillia.me.uk/feeds/4282617702182468787/comments/default' title='Post Comments'/>
<link rel='replies' type='text/html' href='https://www.blogger.com/comment/fullpage/post/2202580486252841248/4282617702182468787' title='0 Comments'/>
<link rel='edit' type='application/atom+xml' href='https://www.blogger.com/feeds/2202580486252841248/posts/default/4282617702182468787'/>
<link rel='self' type='application/atom+xml' href='https://www.blogger.com/feeds/2202580486252841248/posts/default/4282617702182468787'/>
<link rel='alternate' type='text/html' href='https://blog.vexillia.me.uk/2024/09/basing-recipes.html' title='Basing Recipes'/>

<author>
<name>Vexillia</name>
<uri>https://www.blogger.com/profile/06568117694302239705</uri>
<email>noreply@blogger.com</email><gd:image rel='http://schemas.google.com/g/2005#thumbnail' width='32' height='32' src='//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTOHpPdy-qK7_7UGDXenKCbTQsWuPTwpBZ21uIqDj4_PxjlRJA08cW5aioGK5BT39Ku4EoQ0o0pfMq4MMhQGwLYn69_3ESQRkoSnXI93qnUuJmMJha-90aP9vuJY-K3xfeUcgyn_fvZzoejqFgao0kwYALZZmTDS2TWnwpTzQjfKgUAm4/s220/20220123%20-%20Be%20Pure.jpg'/>
</author>

<media:thumbnail xmlns:media='http://search.yahoo.com/mrss/' url='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXoeI0j_FxZAolS7rbW-CfC3ZQB28eUBkz4A7A2OoCLk3NGn1Vc_4RZ4Tg48LDGzHoIpibPoQ5e3IW0IA7zVakDlajPdGN8w9B1a25KKwcnwYig8or0Pn0qI1cRwaWkUmXSptyJ1dHUCwNfsFwZucqO3wb4oWJBBq1Gj6vqQbAI84M0AZirU7Ro8DU866n/s72-c/20220204%20-%20%20S8001954f.JPG' height='72' width='72'/><thr:total>0</thr:total></entry>

<entry>
<id>tag:blogger.com,1999:blog-2202580486252841248.post-4863971468292128007</id>
<published>2024-09-10T18:00:00.006+01:00</published>
<updated>2024-10-31T18:23:28.866Z</updated>
<category scheme='http://www.blogger.com/atom/ns#' term='Ancients'/>
<category scheme='http://www.blogger.com/atom/ns#' term='ADLG'/>
<category scheme='http://www.blogger.com/atom/ns#' term='On Tour'/>
<title type='text'>ADLG: Northern League Round 4 (Manchester, 08 September 2024) </title>
<content type='html'>
```

Here's the full feed:

[view-source_https___www.blogger.com_feeds_2202580486252841248_posts_default.txt](https://github.com/user-attachments/files/17737120/view-source_https___www.blogger.com_feeds_2202580486252841248_posts_default.txt)

Hope this helps.  BTW it's Blogger feed.

**Comment by woodruffw** [comment]
Thanks, that is indeed helpful -- the `<category />` listings there *look* right, so I'll try and debug this some more later.

**Comment by vexillia** [comment]
Any luck?

**Comment by woodruffw** [comment]
> Any luck?

Sorry, but I can't reproduce any tagging issues here. Here's what I see when I use your RSS feed with a dummy backend:

```
$ autopost atom https://feeds.feedburner.com/TheWavingFlag
DUMMY (dummy): content='ADLG: King In The North (York, 19 - 20 Oct 2024)' url='http://blog.vexillia.me.uk/2024/10/adlg-king-in-north-york-14-15-oct-2023.html' tags=['ADLG', 'Ancients', 'On Tour']
🎉 dummy: http://blog.vexillia.me.uk/2024/10/adlg-king-in-north-york-14-15-oct-2023.html
```

Based on that output, the tags are present.

I also tried with the other feed URL, and it also works:

```
$ autopost atom https://www.blogger.com/feeds/2202580486252841248/posts/default/4282617702182468787
DUMMY (dummy): content='Basing Recipes' url='https://blog.vexillia.me.uk/2024/09/basing-recipes.html' tags=['Hobby', 'Tips']
🎉 dummy: https://blog.vexillia.me.uk/2024/09/basing-recipes.html
```

note `tags=['Hobby', 'Tips']` in the output there.

**Comment by vexillia** [comment]
I also tested this:

`autopost --config-file /home/vexillia/.autopost.toml manual "test" --url https://www.blogger.com/feeds/2202580486252841248/posts/default --tags ADLG `

again no tags:

![Screenshot_2024-11-18_09-31-21](https://github.com/user-attachments/assets/b982d20c-300a-4fca-a853-c19f3857c48e)

**Comment by woodruffw** [comment]
Oh, looks like this is a bug specifically in the Bluesky backend -- we don't emit tags there at all. I'll see what can be done there.

**Comment by woodruffw** [comment]
Looks like I need to call [`tag()`](https://atproto.blue/en/latest/atproto/atproto_client.utils.html#atproto_client.utils.TextBuilder.tag) once per listed tag.

**Comment by vexillia** [comment]
Morning!  Any luck unravelling the Bluesky API calls for tags?

**Comment by woodruffw** [comment]
Done with https://github.com/woodruffw/autopost/commit/73df7bdeced4a3487b6775c3eb1fdb4b551f2bec -- I'll make a release shortly.

**Comment by vexillia** [comment]
Confirmed with v0.9 and thanks.
